name: vnf-app
region: sgp
services:
- name: vnf
  github:
    branch: main
    deploy_on_push: true
  build_command: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan db:seed --class=UserSeeder --force
  run_command: heroku-php-apache2 public/
  http_port: 8080
  instance_size_slug: basic-xxs
  instance_count: 1
  envs:
  - key: APP_NAME
    value: "V&F Ice Plant"
  - key: APP_ENV
    value: production
  - key: APP_KEY
    value: "REPLACE_WITH_APP_KEY"
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: https://vnfstotomas.app
  - key: ASSET_URL
    value: https://vnf-app-93blz.ondigitalocean.app
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: "db-mysql-sgp1-27082-do-user-28294724-0.g.db.ondigitalocean.com"
  - key: DB_PORT
    value: "25060"
  - key: DB_DATABASE
    value: defaultdb
  - key: DB_USERNAME
    value: doadmin
  - key: DB_PASSWORD
    value: "REPLACE_WITH_PASSWORD"
  - key: DB_SSL_MODE
    value: preferred
  - key: SESSION_DRIVER
    value: database
  - key: QUEUE_CONNECTION
    value: database
  - key: CACHE_STORE
    value: file
  - key: FILESYSTEM_DISK
    value: local
  - key: LOG_CHANNEL
    value: stack
  - key: LOG_LEVEL
    value: error
  - key: MAIL_MAILER
    value: "null"
  - key: RECAPTCHA_SITE_KEY
    value: "6Ld2Y2wsAAAAAMUTZ8AW2B3ipz0WmOKq0uJdQrGG"
  - key: RECAPTCHA_SECRET_KEY
    value: "6Ld2Y2wsAAAAAEEozE7YXLsnHmv6B1gszpvSlQbS"
